apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: core-cert-manager
  project: default
  source:
    chart: cert-manager
    helm:
      parameters:
        - name: "installCRDs"
          value: "true"
      values: |
        resources:
          - apiVersion: v1
            kind: Namespace
            metadata:
              labels:
                app.kubernetes.io/managed-by: argocd
                app.kubernetes.io/name: core-cert-manager
                app.kubernetes.io/component: namespace
              name: core-cert-manager
      # valueFiles:
      #   - values-ha-prod.yaml
    repoURL: https://charts.jetstack.io
    targetRevision: v1.6.1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false