apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubed
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: core-kubed
  project: default
  source:
    chart: kubed
    helm:
      parameters:
        - name: "enableAnalytics"
          value: "false"
        - name: "operator.resources.limits.cpu"
          value: "100m"
        - name: "operator.resources.limits.memory"
          value: "128Mi"
        - name: "operator.resources.requests.cpu"
          value: "50m"
        - name: "operator.resources.requests.memory"
          value: "128Mi"
        - name: "config.clusterName"
          value: "woot"
      values: |
        resources:
          limits:
            cpu: "82m"
      # valueFiles:
      #   - values-ha-prod.yaml
    repoURL: https://charts.appscode.com/stable
    targetRevision: v0.13.2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
