apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubed
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: core-kubed
  project: default
  source:
    chart: kubed
    helm:
      parameters:
        - name: "resources.limits.cpu"
          value: "71m"
        - name: "resources.limits.blah"
          value: "71m"
        - name: "enableAnalytics"
          value: "false"
        - name: "config.clusterName"
          value: "woot"
      valueFiles:
        - values-ha-prod.yaml
    repoURL: https://tiej-dr.github.io/tiej-charts
    targetRevision: v0.12.0
  syncPolicy:
    automated:
      prune: false
      selfHeal: false